#! /usr/bin/env python

import subprocess
import pty
import sys
import re
from ollama import chat
from ollama import ChatResponse
from termcolor import cprint

# ANSI escape codes
BLUE = "\033[94m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
MAGENTA = "\033[95m"
RESET = "\033[0m"

def highlight_fish_command(cmd: str) -> str:
	tokens = cmd.split()

	highlighted = []

	for i, token in enumerate(tokens):

		# First token = executable (blue)
		if i == 0:
			highlighted.append(f"{BLUE}{token}{RESET}")
			continue

		# Strings = yellow
		if re.fullmatch(r"'.*?'|\".*?\"", token):
			highlighted.append(f"{YELLOW}{token}{RESET}")
			continue

		# Flags = green
		if token.startswith("-"):
			highlighted.append(f"{GREEN}{token}{RESET}")
			continue

		# Pipe = blue
		if token == "|":
			highlighted.append(f"{BLUE}{token}{RESET}")
			continue

		# Redirection
		if token in (">", "<", ">>", "2>", "2>>"):
			highlighted.append(f"{MAGENTA}{token}{RESET}")
			continue

		# No match → leave normal
		highlighted.append(token)

	return " ".join(highlighted)

def get_response(prompt):
	# Build a single message string including instructions and the logs
	user_prompt = (
		f"""
Below is a request from a user in search of the correct fish command in an arch based system. please respond with only the correct command without any additional text. Assume your response will be run exactly as outputted in a terminal.
User Request:{prompt}
"""
	)
	messages = [{"role": "user", "content": user_prompt},]
	response: ChatResponse = chat(model="gpt-oss:20b", messages=messages)

	# Print the mapped content field from the response object
	try:
		return response.message.content
	except Exception:
		# Fallback if response object shape differs
		return response

def check_command_danger(cmd):
	# Build a single message string including instructions and the logs
	user_prompt = (
		f"""
below is a command generated by an AI assistant for a fish shell in an arch based system. please respond with only "yes" if the command is correct and will run without error, or "no" if the command will produce an error or make a permanent change to the system. Assume your response will be read exactly as outputted. respond with only yes or no.
command :{cmd}
"""
	)
	messages = [{"role": "user", "content": user_prompt},]
	response: ChatResponse = chat(model="gpt-oss:20b", messages=messages)

	# Print the mapped content field from the response object
	try:
		yn = response.message.content
	except Exception:
		# Fallback if response object shape differs
		yn = response
	if "yes" in yn.lower():
		return True
	return False

if __name__ == "__main__":
	user_input = sys.argv[1:]
	print()
	cprint("AIagent@GPToss $ ", 'magenta', end="", flush=True)
	command = (get_response(f"""{user_input}"""))

	print (highlight_fish_command(command), end ="", flush=True)
	if not check_command_danger(command):
		check = input(" (Press Enter to run)")
		if check == "":
			pty.spawn (["fish", "-i", "-c", command])
		else:
			sys.exit
	else:
		print()
		pty.spawn (["fish", "-i", "-c", command])